packages:
  - "."

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64

allowBuilds:
  "@prisma/engines": true
  "@sentry/cli": true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - unrs-resolver
